### ISSUE TITLE
Remove / rename Alias '?'

### ISSUE THREAD

**Issue by Stephanevg** [StartAutomating/Splatter#1]
Hi, I read in the documenttion that the Alias for Get-Splat is '?'.

The '?' sign is already an alias for 'Where-Object'. this is a conflict with an alias that has been in Powershell since the begining

I would recommend to change the alias to something else.

**Comment by lucdekens** [comment]
Isn't the alias '?@'

**Comment by StartAutomating** [comment]
The alias is ?@.  Think of it like "Where-Splat".
